package Presentation;

import Business.BusinessFacade;
import EDA.Arma;
import EDA.Armadura;
import EDA.Equipamento;
import EDA.Itens;
import EDA.Personagem;
import EDA.Usuario;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pixel
 */
public class TelaInventario extends javax.swing.JFrame {
    Usuario usuarioLogado = BusinessFacade.getUsuarioLogado();
    Personagem personagem = usuarioLogado.getPersonagem();
    ArrayList<Itens> arrayPocao = new ArrayList<>();
    int xPlayer;
    int yPlayer;
    /**
     * Creates new form TelaInventario
     */
    public TelaInventario(int xPlayer, int yPlayer) {
        initComponents();
        this.xPlayer = xPlayer;
        this.yPlayer = yPlayer;
        labelArma.setText(personagem.getArma().getNome());
        labelElmo.setText(personagem.getElmo().getNome());
        labelPeito.setText(personagem.getPeito().getNome());
        labelBota.setText(personagem.getBota().getNome());
        
        DefaultTableModel modelo = new DefaultTableModel(
            new Object [][]{},
            new String []{"Nome", "Lvl", "Dano/Proteção", "Preço"}
        );

        DefaultTableModel modelo3 = new DefaultTableModel(
            new Object [][]{},
            new String[] {"Tipo", "Eficiencia", "Quantidade", "Preço"}
        );
        
        tabelaEquipamento.setModel(modelo);
        tabelaPocao.setModel(modelo3);
        
        if(tabelaEquipamento.getModel() instanceof DefaultTableModel){
            Iterator it = personagem.getInventario().iterator();
            while(it.hasNext()){
                Equipamento equip = (Equipamento) it.next();
                modelo.addRow(new Object[]{equip.getNome(), equip.getLvl(), equip.getPropriedade(), equip.getValorCompra()});
            }
        }
        
        if(tabelaPocao.getModel() instanceof DefaultTableModel){
            Iterator itItens = arrayPocao.iterator();
            while(itItens.hasNext()){
                Itens itens = (Itens) itItens.next();
                modelo3.addRow(new Object[]{itens.getTipo(), itens.getEficiencia(), itens.getQuantidade(), itens.getValorCompra()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEquipamento = new javax.swing.JTable();
        labelArma = new javax.swing.JLabel();
        labelElmo = new javax.swing.JLabel();
        labelPeito = new javax.swing.JLabel();
        labelBota = new javax.swing.JLabel();
        botaoExcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPocao = new javax.swing.JTable();
        buttonVoltar = new javax.swing.JButton();
        buttonEquipar = new javax.swing.JButton();
        labelImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(881, 518));
        setPreferredSize(new java.awt.Dimension(881, 518));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setText("Inventario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 0, 320, 40);

        tabelaEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEquipamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEquipamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEquipamento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 430, 240);

        labelArma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelArma.setForeground(new java.awt.Color(255, 0, 0));
        labelArma.setText("we");
        getContentPane().add(labelArma);
        labelArma.setBounds(290, 300, 280, 20);

        labelElmo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelElmo.setForeground(new java.awt.Color(255, 0, 0));
        labelElmo.setText("we");
        getContentPane().add(labelElmo);
        labelElmo.setBounds(290, 330, 280, 20);

        labelPeito.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPeito.setForeground(new java.awt.Color(255, 0, 0));
        labelPeito.setText("we");
        getContentPane().add(labelPeito);
        labelPeito.setBounds(290, 360, 290, 20);

        labelBota.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelBota.setForeground(new java.awt.Color(255, 0, 0));
        labelBota.setText("we");
        getContentPane().add(labelBota);
        labelBota.setBounds(290, 390, 300, 20);

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(720, 440, 100, 40);

        tabelaPocao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaPocao);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(470, 40, 390, 240);

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVoltar);
        buttonVoltar.setBounds(60, 450, 90, 30);

        buttonEquipar.setText("Equipar");
        buttonEquipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEquiparActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEquipar);
        buttonEquipar.setBounds(60, 350, 73, 23);

        labelImgFundo.setText("jLabel2");
        getContentPane().add(labelImgFundo);
        labelImgFundo.setBounds(0, 0, 880, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaEquipamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEquipamentoMouseClicked
        //if(tabelaArma.getSelectedRow() != -1){
            /*Armadura delete;
            int index = tabelaEquipamento.getSelectedRow();
            delete = delete + arrayEquipamento;
            labelValor.setText("" + valortotal);*/
        //}
    }//GEN-LAST:event_tabelaEquipamentoMouseClicked

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if(tabelaEquipamento.getSelectedRow() != -1){
            int i = tabelaEquipamento.getSelectedRow();
            personagem.getInventario().remove(i);//chama o array com .remove
            TelaInventario telaIn = new TelaInventario(xPlayer, yPlayer);
            telaIn.setVisible(true);//abre a tela
            this.dispose();//fecha a tela
        } else if(tabelaPocao.getSelectedRow() != -1){
            int i = tabelaPocao.getSelectedRow();
            arrayPocao.remove(i);
            TelaInventario telaIn = new TelaInventario(xPlayer, yPlayer);
            telaIn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        TelaMundo tela = new TelaMundo(xPlayer, yPlayer);
        Main.abrir(tela);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonEquiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEquiparActionPerformed
        if(tabelaEquipamento.getSelectedRow() != -1){
            int i = tabelaEquipamento.getSelectedRow();
            if(personagem.getInventario().get(i) instanceof Arma){
                Arma aux = personagem.getArma();
                Arma novaArma = (Arma) personagem.getInventario().get(i);
                personagem.setArma(novaArma);
                personagem.getInventario().add(aux);
                personagem.getInventario().remove(i);
                TelaInventario telaIn = new TelaInventario(xPlayer, yPlayer);
                telaIn.setVisible(true);//abre a tela
                this.dispose();//fecha a tela
            }    
                
        }
    }//GEN-LAST:event_buttonEquiparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton buttonEquipar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelArma;
    private javax.swing.JLabel labelBota;
    private javax.swing.JLabel labelElmo;
    private javax.swing.JLabel labelImgFundo;
    private javax.swing.JLabel labelPeito;
    private javax.swing.JTable tabelaEquipamento;
    private javax.swing.JTable tabelaPocao;
    // End of variables declaration//GEN-END:variables
}
