
package Presentation;

import Business.BusinessFacade;
import EDA.Monstro;
import EDA.Personagem;
import EDA.Usuario;

/**
 *
 * @author pixel
 */
public class TelaBatalha extends javax.swing.JFrame {
    Monstro monstro;
    Usuario usuarioLogado = BusinessFacade.getUsuarioLogado();
    Personagem personagem = usuarioLogado.getPersonagem();

    public TelaBatalha(Monstro monstro) {
        initComponents();
        this.monstro = monstro;
        barraHP.setValue(personagem.getHp());
        if(this.monstro.getNome().contains("Terminator")){
            labelBicho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undo.png")));
            labelFala.setText("Vou te pegar");
        } else if(this.monstro.getNome().contains("Zumbi")){
            labelBicho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undo (2).png")));
            labelFala.setText("Rarharhahhrara");
        } else if(this.monstro.getNome().contains("sasuke")){
            labelBicho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sasuke.png")));
            labelFala.setText("VEM ME DAR CABEÇADAAAAAAAAA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInfoHP = new javax.swing.JLabel();
        buttonDefender = new javax.swing.JButton();
        buttonAtacar = new javax.swing.JButton();
        buttonPocao = new javax.swing.JButton();
        buttonFugir = new javax.swing.JButton();
        barraHP = new javax.swing.JProgressBar();
        labelFala = new javax.swing.JLabel();
        labelBicho = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(656, 529));
        setMinimumSize(new java.awt.Dimension(656, 529));
        setPreferredSize(new java.awt.Dimension(656, 529));
        setResizable(false);
        getContentPane().setLayout(null);

        labelInfoHP.setText("HP:");
        getContentPane().add(labelInfoHP);
        labelInfoHP.setBounds(20, 460, 17, 14);

        buttonDefender.setText("Defender");
        buttonDefender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefenderActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDefender);
        buttonDefender.setBounds(180, 410, 80, 23);

        buttonAtacar.setText("Atacar");
        buttonAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtacarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtacar);
        buttonAtacar.setBounds(20, 410, 65, 23);

        buttonPocao.setText("Usar poções");
        buttonPocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPocaoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPocao);
        buttonPocao.setBounds(360, 410, 100, 23);

        buttonFugir.setText("Fugir");
        buttonFugir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFugirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFugir);
        buttonFugir.setBounds(560, 410, 57, 23);

        barraHP.setBackground(new java.awt.Color(0, 0, 0));
        barraHP.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(barraHP);
        barraHP.setBounds(40, 460, 146, 20);

        labelFala.setFont(new java.awt.Font("Chiller", 0, 48)); // NOI18N
        labelFala.setForeground(new java.awt.Color(255, 255, 255));
        labelFala.setText("Vem pro pau cuzão");
        getContentPane().add(labelFala);
        labelFala.setBounds(10, 10, 640, 50);

        labelBicho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBicho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undo.png"))); // NOI18N
        getContentPane().add(labelBicho);
        labelBicho.setBounds(30, 0, 620, 390);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dungeonFloor.jpg"))); // NOI18N
        background1.setText("jLabel2");
        getContentPane().add(background1);
        background1.setBounds(0, 330, 650, 60);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dungeonWall.jpg"))); // NOI18N
        background2.setText("jLabel1");
        getContentPane().add(background2);
        background2.setBounds(0, 0, 650, 330);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundCriacaoPersonagem.jpg"))); // NOI18N
        background3.setText("jLabel3");
        background3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(background3);
        background3.setBounds(0, 390, 650, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPocaoActionPerformed

    private void buttonAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtacarActionPerformed
        personagem.atacar(monstro);
        monstro.turno(personagem);
    }//GEN-LAST:event_buttonAtacarActionPerformed

    private void buttonDefenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefenderActionPerformed
        personagem.setDefesa(true);
    }//GEN-LAST:event_buttonDefenderActionPerformed

    private void buttonFugirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFugirActionPerformed
        TelaMundo tela = new TelaMundo();
        Main.abrir(tela);
        this.dispose();
    }//GEN-LAST:event_buttonFugirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JProgressBar barraHP;
    private javax.swing.JButton buttonAtacar;
    private javax.swing.JButton buttonDefender;
    private javax.swing.JButton buttonFugir;
    private javax.swing.JButton buttonPocao;
    private javax.swing.JLabel labelBicho;
    private javax.swing.JLabel labelFala;
    private javax.swing.JLabel labelInfoHP;
    // End of variables declaration//GEN-END:variables
}
