/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author pixel
 */
public class TelaBatalha extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha() {
        initComponents();
        barraHP.setValue(100);
        for(int i = 0; i < 100; i++){
           barraHP.setValue(100 - i); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        barraHP = new javax.swing.JProgressBar();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(656, 529));
        setMinimumSize(new java.awt.Dimension(656, 529));
        setPreferredSize(new java.awt.Dimension(656, 529));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("HP:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 460, 17, 14);

        jButton2.setText("Defender");
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 410, 80, 23);

        jButton1.setText("Atacar");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 410, 65, 23);

        jButton3.setText("Usar poções");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 410, 100, 23);

        jButton4.setText("Fugir");
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 410, 57, 23);

        barraHP.setBackground(new java.awt.Color(0, 0, 0));
        barraHP.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(barraHP);
        barraHP.setBounds(40, 460, 146, 20);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dungeonFloor.jpg"))); // NOI18N
        background1.setText("jLabel2");
        getContentPane().add(background1);
        background1.setBounds(0, 330, 650, 60);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dungeonWall.jpg"))); // NOI18N
        background2.setText("jLabel1");
        getContentPane().add(background2);
        background2.setBounds(0, 0, 650, 330);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundCriacaoPersonagem.jpg"))); // NOI18N
        background3.setText("jLabel3");
        background3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(background3);
        background3.setBounds(0, 390, 650, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JProgressBar barraHP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
